### ISSUE TITLE
`write_ods` testing all edge cases

### ISSUE THREAD

**Issue by chainsawriot** [ropensci/readODS#142]
* [x] empty tibble / data frame (`tibble::tibble()`) #148
* [x] zero row (but with column information) #148
* [ ] Only with rownames and colnames
* [ ] list columns (? error)
* [x] zero row (but with column information) but `col_names` = `FALSE` #148

**Comment by chainsawriot** [comment]
Expected behaviors

List column is handled differently.

``` r
require(writexl)
#> Loading required package: writexl

empty <- tibble::tibble()

zero_rows <- tibble::tibble(mtcars[0,])

all_na <- mtcars[,1, drop = FALSE]
all_na[,1] <- NA

lc_test <- tibble::tibble(mtcars)
lc_test$lc <- strsplit(rownames(mtcars), " ")

readxl::read_xlsx(writexl::write_xlsx(empty))
#> # A tibble: 0 × 0

readxl::read_xlsx(writexl::write_xlsx(zero_rows))
#> # A tibble: 0 × 11
#> # ℹ 11 variables: mpg <lgl>, cyl <lgl>, disp <lgl>, hp <lgl>, drat <lgl>,
#> #   wt <lgl>, qsec <lgl>, vs <lgl>, am <lgl>, gear <lgl>, carb <lgl>

readxl::read_xlsx(writexl::write_xlsx(all_na))
#> # A tibble: 0 × 1
#> # ℹ 1 variable: mpg <lgl>

readxl::read_xlsx(writexl::write_xlsx(lc_test))
#> # A tibble: 32 × 12
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb lc   
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <lgl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4 NA   
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4 NA   
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1 NA   
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1 NA   
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2 NA   
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1 NA   
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4 NA   
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2 NA   
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2 NA   
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4 NA   
#> # ℹ 22 more rows

temp <- tempfile(fileext = ".xlsx")
openxlsx::write.xlsx(empty, temp)
readxl::read_xlsx(temp)
#> # A tibble: 0 × 0

temp <- tempfile(fileext = ".xlsx")
openxlsx::write.xlsx(zero_rows, temp)
readxl::read_xlsx(temp)
#> # A tibble: 0 × 11
#> # ℹ 11 variables: mpg <lgl>, cyl <lgl>, disp <lgl>, hp <lgl>, drat <lgl>,
#> #   wt <lgl>, qsec <lgl>, vs <lgl>, am <lgl>, gear <lgl>, carb <lgl>

temp <- tempfile(fileext = ".xlsx")
openxlsx::write.xlsx(all_na, temp)
readxl::read_xlsx(temp)
#> # A tibble: 0 × 1
#> # ℹ 1 variable: mpg <lgl>

temp <- tempfile(fileext = ".xlsx")
openxlsx::write.xlsx(lc_test, temp)
readxl::read_xlsx(temp)
#> # A tibble: 32 × 12
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb lc         
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4 Mazda, RX4 
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4 Mazda, RX4…
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1 Datsun, 710
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1 Hornet, 4,…
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2 Hornet, Sp…
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1 Valiant    
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4 Duster, 360
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2 Merc, 240D 
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2 Merc, 230  
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4 Merc, 280  
#> # ℹ 22 more rows
```

<sup>Created on 2023-08-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chainsawriot** [comment]
Current behaviors b46a9d0f8c7292d68432d7efc5d899cd2dcd8bf7

``` r
empty <- tibble::tibble()

zero_rows <- tibble::tibble(mtcars[0,])

all_na <- mtcars[,1, drop = FALSE]
all_na[,1] <- NA

lc_test <- tibble::tibble(mtcars)
lc_test$lc <- strsplit(rownames(mtcars), " ")

readODS::read_ods(readODS::write_ods(empty))
#> Error: Invalid input type, expected 'character' actual 'logical'
readODS::read_ods(readODS::write_ods(zero_rows))
#> Warning: Cannot make column/row names if this would cause the dataframe to be
#> empty.
#> # A tibble: 1 × 11
#>   V1    V2    V3    V4    V5    V6    V7    V8    V9    V10   V11  
#>   <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr>
#> 1 mpg   cyl   disp  hp    drat  wt    qsec  vs    am    gear  carb
readODS::read_ods(readODS::write_ods(all_na))
#> Warning: Cannot make column/row names if this would cause the dataframe to be
#> empty.
#> # A tibble: 1 × 1
#>   V1   
#>   <chr>
#> 1 mpg
readODS::read_ods(readODS::write_ods(lc_test))
#> # A tibble: 32 × 12
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb lc         
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>      
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4 "c(\"Mazda…
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4 "c(\"Mazda…
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1 "c(\"Datsu…
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1 "c(\"Horne…
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2 "c(\"Horne…
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1 "Valiant"  
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4 "c(\"Duste…
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2 "c(\"Merc\…
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2 "c(\"Merc\…
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4 "c(\"Merc\…
#> # ℹ 22 more rows
```

<sup>Created on 2023-08-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chainsawriot** [comment]
@pbrohan I was wondering if this warning really needed. Should we move this to the Documentation instead?

https://github.com/ropensci/readODS/blob/b46a9d0f8c7292d68432d7efc5d899cd2dcd8bf7/R/read_ods.R#L2C1-L5

**Comment by pbrohan** [comment]
Sorry I’ve been quiet, it’s been busy, but I’ll try and get back into
things.

My thought was that this would surprise people if they tried to import a
single row and it just refused with default settings and no warning, but
I’ll happily move it!

**Comment by chainsawriot** [comment]
``` r
zero_rows <- tibble::tibble(mtcars[0,])

zero_rows <- tibble::tibble(mtcars[0,])
readxl::read_xlsx(writexl::write_xlsx(zero_rows, col_names = FALSE))
#> # A tibble: 0 × 0

temp <- tempfile(fileext = ".xlsx")
openxlsx::write.xlsx(zero_rows, temp, colNames = FALSE)
readxl::read_xlsx(temp)
#> # A tibble: 0 × 0
```

<sup>Created on 2023-08-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chainsawriot** [comment]
``` r
zero_rows <- tibble::tibble(mtcars[0,])
readODS::read_ods(readODS::write_ods(zero_rows, col_names = FALSE))
#> Warning: empty sheet, return empty data frame.
#> # A tibble: 0 × 0
```

<sup>Created on 2023-08-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chainsawriot** [comment]
This one might be hard to emulate:

``` r
all_na <- mtcars[,1, drop = FALSE]
all_na[,1] <- NA
readxl::read_xlsx(writexl::write_xlsx(all_na))
#> # A tibble: 0 × 1
#> # ℹ 1 variable: mpg <lgl>
readxl::read_xlsx(writexl::write_xlsx(all_na, col_names = FALSE))
#> # A tibble: 0 × 0
```

<sup>Created on 2023-08-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chainsawriot** [comment]
`all_na` cases are surprisingly consistent.

For list-columns, I think a good solution is to say the expected behaviour is undefined ( `writexl` and `openxlsx` deal with them differently) in the documentation.
