### ISSUE TITLE
Tasks for v2.0

### ISSUE THREAD

**Issue by chainsawriot** [ropensci/readODS#63]
Deprecation

- [x] `read.ods`
- [x] `overwrite` argument for `write_ods`
- [x] `getNrOfSheetsInODS`
- [x] `get_num_sheets_in_ods`
- [x] `ods_sheets`
- [x] `getOption("write_ods_na", default = FALSE)` #79 
- [x] `verbose` argument for `write_ods`
- [x] `check_names` #115 

License

- [x] readxl zip (MIT)
- [x] rapidxml (MIT)

Functionalities
- [x] as_tibble
- [x] as_tibble default for v2

Revdep
- [x] check
- [x] submitt prs

misc
- [x] R>=3.5 (as `readr` needs 3.5)

**Comment by chainsawriot** [comment]
I think `get_num_sheets_in_ods` is pretty useless now. Probably it should also be removed in v2.

**Comment by chainsawriot** [comment]
Revdeps

Checkable (via `revdepcheck::revdep_check`)

- [x] `CDSS` - probably due to tibble and `drop`
- [x] `esaps` - removed `ods_sheets` Nicolas-Schmidt/esaps#1

Uncheckable (no test, no example)

- [x] [elementR](https://github.com/charlottesirot/elementR) charlottesirot/elementR#14

**Comment by chainsawriot** [comment]
@pbrohan I tried to submit it just now, but the CRAN team is on their "Sommerpause"; will have to submit it again in the 2nd week of August.

**Comment by pbrohan** [comment]
@chainsawriot Ah, I forgot about sommerpauses, but it can wait :). 

Thanks for all the work you've put into the package, and there are so many additional admin steps I didn't even realise as well!

**Comment by chainsawriot** [comment]
submitted

**Comment by chainsawriot** [comment]
Done. It's on CRAN. For a write up: please [read](https://chainsawriot.com/postmannheim/2023/08/06/readods2.html).
